#!/bin/bash
#
# Clean, build and start server
#
# Andrew DeOrio <awdeorio@umich.edu>

# Stop on errors, print commands
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
set -x

# Runs server
python3 -m http.server 8000

# If everything succeeded, return a zero exit code (success)
exit 0